# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import myproto_pb2 as myproto__pb2


class MyServiceControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/my_service.MyServiceController/SayHello',
                request_serializer=myproto__pb2.Request.SerializeToString,
                response_deserializer=myproto__pb2.Response.FromString,
                )
        self.ProcessMessaging = channel.stream_stream(
                '/my_service.MyServiceController/ProcessMessaging',
                request_serializer=myproto__pb2.Request.SerializeToString,
                response_deserializer=myproto__pb2.Response.FromString,
                )


class MyServiceControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessMessaging(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=myproto__pb2.Request.FromString,
                    response_serializer=myproto__pb2.Response.SerializeToString,
            ),
            'ProcessMessaging': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessMessaging,
                    request_deserializer=myproto__pb2.Request.FromString,
                    response_serializer=myproto__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'my_service.MyServiceController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyServiceController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/my_service.MyServiceController/SayHello',
            myproto__pb2.Request.SerializeToString,
            myproto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessMessaging(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/my_service.MyServiceController/ProcessMessaging',
            myproto__pb2.Request.SerializeToString,
            myproto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
